name: 'Copy'
on:
  push:
    branches:
      - 'main'
jobs:
  copy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: 'Copy'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab
          git push --force --mirror gitlab https://oauth2:${{ secrets.GITLAB_KEY }}@gitlab.com/tegebu/aubergine.git
